name: Fetch Jobs Data

on:
  schedule:
    # Run every weekday at 02:10 and 07:10 UTC (10:10 and 15:10 SGT)
    - cron: '10 2,7 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Fetch job listings
        uses: githubocto/flat@fc34373cc20b987e89d75d96435a9fecd8fb0807
        with:
          http_url: ${{ secrets.CAREERSGOVSG_JOB_HEADER }}
          downloaded_filename: data/job-listings-raw.json
          postprocess: scripts/fetch-jobs.ts
          axios_config: query.json
          mask: true
        env:
          CAREERSGOVSG_JOB_DETAILS: ${{ secrets.CAREERSGOVSG_JOB_DETAILS }}
